### ISSUE TITLE
'vapp_storage_profile' 

### ISSUE THREAD

**Issue by ablease** [cloudfoundry/bosh_vcloud_cpi#17]
Hey, 

We would like to configure our microbosh to provision vms for our delployments with the Gold storage policy. 

`media_storage_profile:` does not cover this, and we would like to set the storage policy across a vapp. 

We have tried setting `vapp_storage_profile: Gold` in both 

```
properties:
  vcd:
    entities:
      vapp_storage_profile: Gold
```

and

```
plugin: vcloud
vcds:
  - entities:
       vapp_storage_profile: Gold
```

in our microbosh deployment manifest, but neither has worked. 

On inspecting the cpi.json file in `/var/vcap/jobs/cpi/config` we saw that this property does not exist. 

Is there support for this? Or are we setting this property in the wrong section of our microbosh deployment manifest.
